# Generated by Django 4.2.6 on 2023-10-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapplication', '0002_courseregistration_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='address',
            field=models.TextField(max_length=100),
        ),
    ]
