# Generated by Django 4.2.6 on 2023-10-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapplication', '0004_alter_courseregistration_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bkash', 'Bkash'), ('nagad', 'Nagad')], max_length=25, null=True),
        ),
    ]
