# Generated by Django 4.2.6 on 2023-10-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapplication', '0005_courseregistration_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseregistration',
            name='courses',
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='courses',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
