# Generated by Django 4.2.6 on 2023-10-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapplication', '0006_remove_courseregistration_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='advance',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
